---
title: "SpringBok Dataset"
author: "Federico Ferrari"
header-includes:
   - \usepackage{multirow}
   - \usepackage{amsmath}
   - \usepackage{bbm}
output: 
  html_document: default
  pdf_document: default
  
---

```{r echo=FALSE, include=FALSE}
library(lasso2)
library(dplyr)
library(rpart)
library(rpart.plot)
library(car)
library(ggthemes)
library(randomForest)
library(devtools)
library(RCurl)
library(gridExtra)
library(plotROC)
library(pROC)
library(isotone)
library(grid)
library(lattice)
library(stargazer)
library(R2jags)
library(ggmcmc)
library(mcmcplots)
library(gdata)
library(MASS)
library(grid)
library(dplyr)
library(arm)
library(knitr)
library(coda)
library(ggplot2)
```

```{r}
df = read.xls("springbok.xls",header = T)
#locnumber and site are exactely the same variables
df = df[,-1]
colnames(df) = c("site","year","date","hour","counts")
df$site = as.factor(df$site)
df$year = as.factor(df$year)

#some grouping 
df_group = df %>%
  group_by(site,year) %>%
  summarise_each(funs(mean(., na.rm=TRUE)), -c(date,hour))

df_group_means = df %>%
  group_by(year) %>%
  summarise_each(funs(mean(., na.rm=TRUE)), -c(date,hour,site))
```

```{r}
#the mean is displayed in black
ggplot()+
  geom_point(data = df_group, aes(x = year, y = counts , col = site))+
  geom_point(data = df_group_means, aes(x = year, y = counts),color="black")


#h = subset(df_group, site == 1)
#ggplot()+
#  geom_histogram(data = h, aes(x = counts))

#density of the counts per year, black is the distribution of counts over
#all years
ggplot()+
  geom_density(data = df, aes(x = counts, group = year, col = year))+
  geom_density(data = df, aes(x = counts), col="black")


#density of the counts per site, black is the distribution of counts over
#all sites
ggplot()+
  geom_density(data = df, aes(x = counts, group = site, col = site))+
  geom_density(data = df, aes(x = counts), col="black")
```


```{r}
#basic lm: are the counts increasing every year?
lm = lm(counts ~ year, data = df)
#summary(lm)
```

1) Reasonable to assume that $x_t | x_{1:t-1} \sim x_t | x_{t-1}$ where $x_t$ is counts
2) Poisson count model? 


```{r}
#poisson count model
#"quasipoisson families differ from the binomial and poisson families only in that the dispersion parameter is not fixed at one"
glm =  glm(counts ~ hour + site*year - 1, data = df, family = "quasipoisson")
#summary(glm)
sum(glm$residuals^2)

glm_p = glm(counts ~ hour + site*year - 1, data = df, family = "poisson")
sum(glm_p$residuals^2)
#exactely the same estimates, they are not discrete because I am regressing the mean of the distribution
plot(glm)
```

```{r}
#bayesian Poisson Model 
poi_mb = bayesglm(counts ~ hour + year*site - 1,data = df, family =quasipoisson(link = "log"))
#summary(poi_mb)
#little improvement in the residuals
sum(poi_mb$residuals^2)
```


```{r}
#Some plotting
influencePlot(glm)

#residual plot
mu_hat_b = predict(poi_mb)
res = resid(poi_mb)
sigma = sigma.hat(poi_mb)
residual.plot(mu_hat_b, res, sigma)

#binned plot
binnedplot(mu_hat_b,res)

#coefplot
#coefplot(poi_mb,col="blue")
```


```{r}
#subsetting data
poi_1990 = glm(counts ~ 1,data = df, family =quasipoisson(link = "log"),subset=(year == 1990))
#summary(poi_1990)
```



```{r}
#Bayesian Logistic model with JAGS
#lm = lm(counts ~ -1 + year + site + hour, data = df)


n = nrow(df)
X = subset(df, select = c(hour))
n_year = length(unique(df$year))
n_site = length(unique(df$site))

data = list(Y = df[,"counts"], 
            X = X,
            n_year = n_year,
            n_site = n_site,
            year = df$year,
            site = df$site,
            p = ncol(X),
            n = n)


#JAGS
rr.model = function() {
  
  for (i in 1:n){
		Y[i] ~ dpois(mu[i])
		mu[i] <- exp(z[i])
		z[i] <- beta[year[i]] + beta1[site[i]] + inprod(X[i,],alpha) + epsilon
  }
  
  epsilon ~ dnorm(0, gamma_eps)
  gamma_eps ~ dgamma(0.5,0.5)
	#alpha0 ~ dnorm(0, 1.0E-6)
	
	for (k in 1:n_year){
    gamma[k] ~ dgamma(0.5,0.5)
    beta[k] ~ dnorm(mu0, gamma[k])
	  #beta[k] ~ dnorm(0, gamma[k])
	}
	
	for (l in 1:n_site){
    gamma1[l] ~ dgamma(0.5,0.5)
    beta1[l] ~ dnorm(0, gamma1[l])
	  #beta[k] ~ dnorm(0, gamma[k])
	}
	
	#this hierarchical specificacation makes everything super slow
  mu0 ~ dnorm(0,0.00001)
  #eta ~ dgamma(0.5,0.5)
  
  
  for (j in 1:p) {
    tau[j] ~ dgamma(0.5,0.5)
    alpha[j] ~ dnorm(0, tau[j])
  }
}

#parameters to monitor
parameters = c("alpha0","alpha","beta","mu0","gamma","beta1","gamma1","eta","tau")

# run jags from R  (see Resources to install)
sim = jags(data, 
           inits=NULL, 
           par=parameters,
           model=rr.model,
           n.iter=10000)
```


```{r}
#Bayesian Logistic model with JAGS
lm = lm(counts ~ -1 + year + site + hour, data = df)
#missing the indicator variable for site 1

X = model.matrix(lm)

n = nrow(df)
#X = subset(df,select=-c(counts,date))


data = list(Y = df[,"counts"], 
            X = X,
            k = ncol(X),
            n = n)


#JAGS
rr.model = function() {
  
  for (i in 1:n){
		Y[i] ~ dpois(mu[i])
		mu[i] <- exp(z[i])
		z[i] <- alpha0 + inprod(X[i,],alpha)
  }
  
	alpha0 ~ dnorm(0, 1.0E-6)

  for (j in 1:k) {
    alpha[j] ~ dnorm(0, 1.0E-6)
  }
}

#parameters to monitor
parameters = c("alpha0","alpha")

# run jags from R  (see Resources to install)
sim = jags(data, 
           inits=NULL, 
           par=parameters,
           model=rr.model,
           n.iter=10000)
```


